### ISSUE TITLE
Fatal error when using PHP 8.0

### ISSUE THREAD

**Issue by GamerMedic** [paragonie/ciphersweet#58]
I get the following error when I update my server to PHP 8.0:

```
PHP Fatal error:  Uncaught Error: Undefined constant "MB_OVERLOAD_STRING" in /home/user/vendor/paragonie/sodium_compat/src/Core/Util.php:915
Stack trace:
#0 /home/user/vendor/paragonie/sodium_compat/src/Core/Util.php(757): ParagonIE_Sodium_Core_Util::isMbStringOverride()
#1 /home/user/vendor/paragonie/sodium_compat/src/Compat.php(893): ParagonIE_Sodium_Core_Util::strlen()
#2 /home/user/vendor/paragonie/ciphersweet/src/Backend/ModernCrypto.php(54): ParagonIE_Sodium_Compat::crypto_aead_xchacha20poly1305_ietf_encrypt()
#3 /home/user/vendor/paragonie/ciphersweet/src/EncryptedField.php(106): ParagonIE\CipherSweet\Backend\ModernCrypto->encrypt()
#4 file.php(88): ParagonIE\CipherSweet\EncryptedField->encryptValue()
#5 file.php(86): ParagonIE\CipherSweet\EncryptedField->prepareForStorage()
#6 file.php(35): customFunction()
#7 {main}
  thrown in /home/user/vendor/paragonie/sodium_compat/src/Core/Util.php on line 915
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'column' cannot be null in file.php:201
Stack trace:
#0 file.php(201): PDOStatement->execute()
#1 {main}
  thrown in file.php
```

My code works perfectly when I revert back to PHP 7.4.

**Comment by paragonie-security** [comment]
Have you installed the mbstring extension in 8.0?

**Comment by GamerMedic** [comment]
> Have you installed the mbstring extension in 8.0?

Hi,

Yes I have. I've included a link to a screenshot of the extensions I have enabled in 8.0.

[PHP8.0 Options Screenshot - ImgBB](https://ibb.co/z4wnt5H)

**Comment by paragonie-security** [comment]
Does updating to the latest version of sodium_compat fix or change the error message?

**Comment by GamerMedic** [comment]
> Does updating to the latest version of sodium_compat fix or change the error message?

I have updated the sodium_compat files, and even gone so far as to uninstall and reinstall ciphersweet. I'm getting the same error message.

**Comment by paragonie-security** [comment]
```php
if (!defined('MB_OVERLOAD_STRING')) define('MB_OVERLOAD_STRING', 0);
```

Here's a workaround until we figure out the exact root cause. Add this to your code that uses CipherSweet (or an autoload file).

**Comment by GamerMedic** [comment]
Thank you. The workaround is working!
